import type { InvestigationGraph } from "@/core/investigation-graph";

const ids = {
  case: "00000000-0000-4000-8000-000000000001",
  owner: "00000000-0000-4000-8000-000000000002",
  rootBranch: "00000000-0000-4000-8000-000000000003",
  childBranch: "00000000-0000-4000-8000-000000000004",
  direction: "00000000-0000-4000-8000-000000000005",
  source: "00000000-0000-4000-8000-000000000006",
  snapshot: "00000000-0000-4000-8000-000000000007",
  locator: "00000000-0000-4000-8000-000000000008",
  evidence: "00000000-0000-4000-8000-000000000009",
  claim: "00000000-0000-4000-8000-000000000010",
  claimEdge: "00000000-0000-4000-8000-000000000011",
  provenanceSnapshot: "00000000-0000-4000-8000-000000000012",
  provenanceExtract: "00000000-0000-4000-8000-000000000013",
  provenanceLocator: "00000000-0000-4000-8000-000000000014",
  provenanceClaim: "00000000-0000-4000-8000-000000000015",
  provenanceBranch: "00000000-0000-4000-8000-000000000016",
} as const;

export const TEST_IDS = ids;
export const TEST_TIME = "2026-08-08T12:00:00.000Z";
export const TEST_LATER_TIME = "2026-08-08T12:01:00.000Z";
export const TEST_FINGERPRINT = "a".repeat(64);

export const systemOrigin = {
  kind: "DETERMINISTIC_SYSTEM",
  actorId: "core-test-fixture",
  version: "1.0.0",
} as const;

export const userOrigin = {
  kind: "USER",
  actorId: ids.owner,
  version: null,
} as const;

export function makeValidGraph(): InvestigationGraph {
  return {
    case: {
      id: ids.case,
      ownerId: ids.owner,
      specialistId: "movie-investigator",
      specialistVersion: "1.0.0",
      subjectRef: {
        type: "film",
        id: "tmdb:123",
        versionId: null,
      },
      exactCuriosity: "Why did the plan fail?",
      status: "ACTIVE",
      health: "HEALTHY",
      activeBranchId: ids.rootBranch,
      aggregateVersion: 4,
      eventSequence: 8,
      createdAt: TEST_TIME,
      updatedAt: TEST_LATER_TIME,
    },
    sources: [
      {
        id: ids.source,
        canonicalKey: "isbn:9780000000000",
        canonicalUrl: "https://example.com/books/primary-account",
        title: "A Primary Account",
        contributors: ["Example Author"],
        publisher: "Example Press",
        publishedAt: "2020-01-01T00:00:00.000Z",
        medium: "BOOK",
        sourceClass: "first-hand-account",
        accessState: "OPEN",
        rightsState: "PERMITTED",
        independenceGroupId: "origin:primary-account",
        origin: systemOrigin,
        createdAt: TEST_TIME,
      },
    ],
    snapshots: [
      {
        id: ids.snapshot,
        sourceId: ids.source,
        caseId: ids.case,
        contentFingerprint: TEST_FINGERPRINT,
        contentLength: 1_024,
        extractionMethod: "DETERMINISTIC_FIXTURE",
        storageRef: "fixture:snapshot:primary-account",
        accessState: "OPEN",
        rightsState: "PERMITTED",
        capturedAt: TEST_TIME,
        createdByRunId: null,
        origin: systemOrigin,
      },
    ],
    locators: [
      {
        id: ids.locator,
        sourceId: ids.source,
        kind: "BOOK",
        status: "VERIFIED_EXACT",
        resolver: { id: "fixture-book-resolver", version: "1.0.0" },
        revision: 1,
        supersedesLocatorId: null,
        openUrl: "https://example.com/books/primary-account",
        resolvedAt: TEST_TIME,
        lastVerifiedAt: TEST_LATER_TIME,
        createdAt: TEST_TIME,
        editionId: "edition:test-hardcover",
        isbn: "9780000000000",
        pageStart: 42,
        pageEnd: 43,
        printedPageLabel: "42–43",
        chapter: "The Plan",
        section: null,
      },
    ],
    evidence: [
      {
        id: ids.evidence,
        caseId: ids.case,
        sourceId: ids.source,
        snapshotId: ids.snapshot,
        locatorId: ids.locator,
        finding: "The plan depended on a short operational window.",
        shortQuote: null,
        whySurfaced: "It identifies a dependency in the plan.",
        limitations: ["One participant account"],
        confidence: "MEDIUM",
        reviewState: "ACCEPTED",
        origin: systemOrigin,
        createdByRunId: null,
        createdAt: TEST_LATER_TIME,
      },
    ],
    claims: [
      {
        id: ids.claim,
        caseId: ids.case,
        branchId: ids.rootBranch,
        statement: "The plan depended on completing the operation quickly.",
        epistemicKind: "FACTUAL_CLAIM",
        assessmentState: "SUPPORTED_WITH_LIMITATIONS",
        confidenceLanguage:
          "Supported by one direct account; corroboration remains open.",
        reviewState: "ACCEPTED",
        origin: systemOrigin,
        createdByRunId: null,
        supersedesClaimId: null,
        createdAt: TEST_LATER_TIME,
      },
    ],
    claimEvidenceEdges: [
      {
        id: ids.claimEdge,
        caseId: ids.case,
        claimId: ids.claim,
        evidenceId: ids.evidence,
        polarity: "SUPPORTS",
        rationale: "The account describes the intended short duration.",
        limitations: ["Not independently corroborated in this fixture"],
        reviewState: "ACCEPTED",
        origin: systemOrigin,
        createdByRunId: null,
        createdAt: TEST_LATER_TIME,
      },
    ],
    branches: [
      {
        id: ids.rootBranch,
        caseId: ids.case,
        parentBranchId: null,
        originDirectionId: null,
        kind: "ROOT",
        title: "The failure cascade",
        normalizedObjective: "Identify which dependencies failed and when.",
        status: "OPEN",
        researchAxisIds: ["history-politics"],
        unresolvedQuestions: ["Which dependency failed first?"],
        returnAnchor: null,
        aggregateVersion: 2,
        createdAt: TEST_TIME,
        updatedAt: TEST_LATER_TIME,
      },
      {
        id: ids.childBranch,
        caseId: ids.case,
        parentBranchId: ids.rootBranch,
        originDirectionId: ids.direction,
        kind: "THEORY",
        title: "Fragility before contact",
        normalizedObjective:
          "Test whether the plan was fragile before contact.",
        status: "PROPOSED",
        researchAxisIds: ["history-politics"],
        unresolvedQuestions: ["Does hindsight exaggerate the fragility?"],
        returnAnchor: {
          branchId: ids.rootBranch,
          readingSequenceKey: "000100",
          beatId: null,
        },
        aggregateVersion: 0,
        createdAt: TEST_LATER_TIME,
        updatedAt: TEST_LATER_TIME,
      },
    ],
    directions: [
      {
        id: ids.direction,
        caseId: ids.case,
        sourceBranchId: ids.rootBranch,
        actorId: ids.owner,
        exactUserText: "  I think the plan was fragile before contact.  ",
        requestedAction: "THEORY",
        directionType: "THEORY",
        branchAction: "CREATE",
        acknowledgement: "I’m testing that against the evidence.",
        anchor: {
          branchId: ids.rootBranch,
          beatId: null,
          evidenceId: ids.evidence,
          claimId: ids.claim,
          selectedTextFingerprint: null,
          readingSequenceKey: "000100",
        },
        origin: userOrigin,
        createdAt: TEST_LATER_TIME,
      },
    ],
    provenanceEdges: [
      provenance(
        ids.provenanceSnapshot,
        "SOURCE_SNAPSHOT",
        ids.snapshot,
        "DERIVED_FROM",
        "SOURCE",
        ids.source,
      ),
      provenance(
        ids.provenanceExtract,
        "EVIDENCE",
        ids.evidence,
        "EXTRACTED_FROM",
        "SOURCE_SNAPSHOT",
        ids.snapshot,
      ),
      provenance(
        ids.provenanceLocator,
        "EVIDENCE",
        ids.evidence,
        "LOCATED_BY",
        "LOCATOR",
        ids.locator,
      ),
      provenance(
        ids.provenanceClaim,
        "CLAIM",
        ids.claim,
        "SUPPORTED_BY",
        "EVIDENCE",
        ids.evidence,
      ),
      provenance(
        ids.provenanceBranch,
        "BRANCH",
        ids.childBranch,
        "TRIGGERED_BY",
        "DIRECTION",
        ids.direction,
      ),
    ],
  } as InvestigationGraph;
}

function provenance(
  id: string,
  outputType: string,
  outputId: string,
  relationship: string,
  inputType: string,
  inputId: string,
) {
  return {
    id,
    caseId: ids.case,
    output: { type: outputType, id: outputId },
    input: { type: inputType, id: inputId },
    relationship,
    origin: systemOrigin,
    method: { name: "core-test-fixture", version: "1.0.0" },
    runId: null,
    createdAt: TEST_LATER_TIME,
  };
}
